package com.infinitePossibilities.entity;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table save
 */
public class SaveInfo{

    private String id;

    private String applyno;

    private String userName;

    private String userNumber;

    private String address;

    private Date saveTime;

    private String type;

    private String count;

    private byte[] saveBolb;

    private String saveClob;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    public String getApplyno() {
        return applyno;
    }

    public void setApplyno(String applyno) {
        this.applyno = applyno == null ? null : applyno.trim();
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName == null ? null : userName.trim();
    }

    public String getUserNumber() {
        return userNumber;
    }

    public void setUserNumber(String userNumber) {
        this.userNumber = userNumber == null ? null : userNumber.trim();
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    public Date getSaveTime() {
        return saveTime;
    }

    public void setSaveTime(Date saveTime) {
        this.saveTime = saveTime;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }

    public String getCount() {
        return count;
    }

    public void setCount(String count) {
        this.count = count == null ? null : count.trim();
    }

    public byte[] getSaveBolb() {
        return saveBolb;
    }

    public void setSaveBolb(byte[] saveBolb) {
        this.saveBolb = saveBolb;
    }

    public String getSaveClob() {
        return saveClob;
    }

    public void setSaveClob(String saveClob) {
        this.saveClob = saveClob == null ? null : saveClob.trim();
    }
}