package com.wondersgroup.mapper;

import com.wondersgroup.entity.TbltwoInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component(value = "TbltwoInfoMapper")
public interface TbltwoInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_two
     *
     * @mbg.generated Mon May 17 11:20:53 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_two
     *
     * @mbg.generated Mon May 17 11:20:53 CST 2021
     */
    int insert(TbltwoInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_two
     *
     * @mbg.generated Mon May 17 11:20:53 CST 2021
     */
    TbltwoInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_two
     *
     * @mbg.generated Mon May 17 11:20:53 CST 2021
     */
    List<TbltwoInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_two
     *
     * @mbg.generated Mon May 17 11:20:53 CST 2021
     */
    int updateByPrimaryKey(TbltwoInfo record);
}