package com.wondersgroup.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table consumer
 */
public class ConsumerInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.id
     *
     * @mbg.generated Wed Apr 28 17:23:01 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column consumer.name
     *
     * @mbg.generated Wed Apr 28 17:23:01 CST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.id
     *
     * @return the value of consumer.id
     *
     * @mbg.generated Wed Apr 28 17:23:01 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.id
     *
     * @param id the value for consumer.id
     *
     * @mbg.generated Wed Apr 28 17:23:01 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column consumer.name
     *
     * @return the value of consumer.name
     *
     * @mbg.generated Wed Apr 28 17:23:01 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column consumer.name
     *
     * @param name the value for consumer.name
     *
     * @mbg.generated Wed Apr 28 17:23:01 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}