package com.wondersgroup.mapper;

import com.wondersgroup.entity.TblthreeInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component(value = "TblthreeInfoMapper")
public interface TblthreeInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_three
     *
     * @mbg.generated Mon May 17 11:25:15 CST 2021
     * @param id
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_three
     *
     * @mbg.generated Mon May 17 11:25:15 CST 2021
     */
    int insert(TblthreeInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_three
     *
     * @mbg.generated Mon May 17 11:25:15 CST 2021
     */
    TblthreeInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_three
     *
     * @mbg.generated Mon May 17 11:25:15 CST 2021
     */
    List<TblthreeInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tbl_three
     *
     * @mbg.generated Mon May 17 11:25:15 CST 2021
     */
    int updateByPrimaryKey(TblthreeInfo record);
}