package com.wondersgroup.mapper;

import com.wondersgroup.entity.ProducerInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component(value = "ProducerInfoMapper")
public interface ProducerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producer
     *
     * @mbg.generated Wed Apr 28 16:23:49 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producer
     *
     * @mbg.generated Wed Apr 28 16:23:49 CST 2021
     */
    int insert(ProducerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producer
     *
     * @mbg.generated Wed Apr 28 16:23:49 CST 2021
     */
    ProducerInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producer
     *
     * @mbg.generated Wed Apr 28 16:23:49 CST 2021
     */
    List<ProducerInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table producer
     *
     * @mbg.generated Wed Apr 28 16:23:49 CST 2021
     */
    int updateByPrimaryKey(ProducerInfo record);
}