package com.infinitePossibilities.mapper;

import com.infinitePossibilities.entity.Tb_User_Info;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component(value = "Tb_User_InfoMapper")
public interface Tb_User_InfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Tue Jun 01 14:04:13 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Tue Jun 01 14:04:13 CST 2021
     */
    int insert(Tb_User_Info record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Tue Jun 01 14:04:13 CST 2021
     */
    Tb_User_Info selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Tue Jun 01 14:04:13 CST 2021
     */
    List<Tb_User_Info> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tb_user
     *
     * @mbg.generated Tue Jun 01 14:04:13 CST 2021
     */
    int updateByPrimaryKey(Tb_User_Info record);
}