package com.infinitePossibilities.aop_mybatis.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table xuehua
 */
public class XueHuaInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuehua.id
     *
     * @mbg.generated Thu Apr 22 14:01:30 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column xuehua.name
     *
     * @mbg.generated Thu Apr 22 14:01:30 CST 2021
     */
    private String name;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuehua.id
     *
     * @return the value of xuehua.id
     *
     * @mbg.generated Thu Apr 22 14:01:30 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuehua.id
     *
     * @param id the value for xuehua.id
     *
     * @mbg.generated Thu Apr 22 14:01:30 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column xuehua.name
     *
     * @return the value of xuehua.name
     *
     * @mbg.generated Thu Apr 22 14:01:30 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column xuehua.name
     *
     * @param name the value for xuehua.name
     *
     * @mbg.generated Thu Apr 22 14:01:30 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }
}