package com.infinitePossibilities.dao;

import lombok.Data;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;


/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table save
 */
@Entity
@Table(name="save")
@Data
public class Save {
    /**
     * Database Column Remarks:
     * 主键id
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column save.ID
     *
     * @mbg.generated Tue Dec 01 11:02:58 CST 2020
     */
    @Id
    private Long id;

    /**
     * Database Column Remarks:
     * 办件编号
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column save.APPLYNO
     *
     * @mbg.generated Tue Dec 01 11:02:58 CST 2020
     */
    private String applyno;

    /**
     * Database Column Remarks:
     * 办理人名称
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column save.USER_NAME
     *
     * @mbg.generated Tue Dec 01 11:02:58 CST 2020
     */

    private String username;

    /**
     * Database Column Remarks:
     * 办理人证件号码
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column save.USER_NUMBER
     *
     * @mbg.generated Tue Dec 01 11:02:58 CST 2020
     */
    private String usernumber;

    /**
     * Database Column Remarks:
     * 办理人地址
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column save.ADDRESS
     *
     * @mbg.generated Tue Dec 01 11:02:58 CST 2020
     */
    private String address;


    /**
     * Database Column Remarks:
     * 办理状态
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column save.TYPE
     *
     * @mbg.generated Tue Dec 01 11:02:58 CST 2020
     */
    private Long type;

    /**
     * Database Column Remarks:
     * 综合信息
     * <p>
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column save.COUNT
     *
     * @mbg.generated Tue Dec 01 11:02:58 CST 2020
     */
    private String count;



}