package com.wondersgroup.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table aopexs
 */
public class AopExsInfo {



    private String id;

    private String cupSize;

    private Integer age;

    private Double money;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aopexs.id
     *
     * @return the value of aopexs.id
     *
     * @mbg.generated Mon Dec 28 11:13:44 CST 2020
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aopexs.id
     *
     * @param id the value for aopexs.id
     *
     * @mbg.generated Mon Dec 28 11:13:44 CST 2020
     */
    public void setId(String id){
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aopexs.cup_size
     *
     * @return the value of aopexs.cup_size
     *
     * @mbg.generated Mon Dec 28 11:13:44 CST 2020
     */
    public String getCupSize(){
        return cupSize;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aopexs.cup_size
     *
     * @param cupSize the value for aopexs.cup_size
     *
     * @mbg.generated Mon Dec 28 11:13:44 CST 2020
     */
    public void setCupSize(String cupSize) {
        this.cupSize = cupSize == null ? null : cupSize.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aopexs.age
     *
     * @return the value of aopexs.age
     *
     * @mbg.generated Mon Dec 28 11:13:44 CST 2020
     */
    public Integer getAge() {
        return age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aopexs.age
     *
     * @param age the value for aopexs.age
     *
     * @mbg.generated Mon Dec 28 11:13:44 CST 2020
     */
    public void setAge(Integer age) {
        this.age = age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column aopexs.money
     *
     * @return the value of aopexs.money
     *
     * @mbg.generated Mon Dec 28 11:13:44 CST 2020
     */
    public Double getMoney() {
        return money;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column aopexs.money
     *
     * @param money the value for aopexs.money
     *
     * @mbg.generated Mon Dec 28 11:13:44 CST 2020
     */
    public void setMoney(Double money) {
        this.money = money;
    }

    @Override
    public String toString() {
        return "AopExsInfo{" +
                "id=" + id +
                ", cupSize='" + cupSize + '\'' +
                ", age=" + age +
                ", money=" + money +
                '}';
    }
}