package com.wondersgroup.entity;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table localtable
 */
public class LocalTableInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column localtable.id
     *
     * @mbg.generated Thu Apr 29 18:03:24 CST 2021
     */
    private String id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column localtable.type
     *
     * @mbg.generated Thu Apr 29 18:03:24 CST 2021
     */
    private String type;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column localtable.id
     *
     * @return the value of localtable.id
     *
     * @mbg.generated Thu Apr 29 18:03:24 CST 2021
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column localtable.id
     *
     * @param id the value for localtable.id
     *
     * @mbg.generated Thu Apr 29 18:03:24 CST 2021
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column localtable.type
     *
     * @return the value of localtable.type
     *
     * @mbg.generated Thu Apr 29 18:03:24 CST 2021
     */
    public String getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column localtable.type
     *
     * @param type the value for localtable.type
     *
     * @mbg.generated Thu Apr 29 18:03:24 CST 2021
     */
    public void setType(String type) {
        this.type = type == null ? null : type.trim();
    }
}