package com.wondersgroup.mapper;

import com.wondersgroup.entity.ConsumerInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component(value = "ConsumerInfoMapper")
public interface ConsumerInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Wed Apr 28 17:23:01 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Wed Apr 28 17:23:01 CST 2021
     */
    int insert(ConsumerInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Wed Apr 28 17:23:01 CST 2021
     */
    ConsumerInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Wed Apr 28 17:23:01 CST 2021
     */
    List<ConsumerInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table consumer
     *
     * @mbg.generated Wed Apr 28 17:23:01 CST 2021
     */
    int updateByPrimaryKey(ConsumerInfo record);
}