package com.wondersgroup.mapper;

import com.wondersgroup.entity.AopExsInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component(value = "AopExsInfoMapper")
public interface AopExsInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aopexs
     *
     * @mbg.generated Mon Dec 28 11:13:44 CST 2020
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aopexs
     *
     * @mbg.generated Mon Dec 28 11:13:44 CST 2020
     */
    int insert(AopExsInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aopexs
     *
     * @mbg.generated Mon Dec 28 11:13:44 CST 2020
     */
    AopExsInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aopexs
     *
     * @mbg.generated Mon Dec 28 11:13:44 CST 2020
     */
    List<AopExsInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table aopexs
     *
     * @mbg.generated Mon Dec 28 11:13:44 CST 2020
     */
    int updateByPrimaryKey(AopExsInfo record);

    int updateByPrimaryKey2(AopExsInfo record);

    List<AopExsInfo> selectNew(String New);
}