package com.wondersgroup.mapper;

import com.wondersgroup.entity.LocalTableInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component(value = "LocalTableInfoMapper")
public interface LocalTableInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localtable
     *
     * @mbg.generated Thu Apr 29 18:03:24 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localtable
     *
     * @mbg.generated Thu Apr 29 18:03:24 CST 2021
     */
    int insert(LocalTableInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localtable
     *
     * @mbg.generated Thu Apr 29 18:03:24 CST 2021
     */
    LocalTableInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localtable
     *
     * @mbg.generated Thu Apr 29 18:03:24 CST 2021
     */
    List<LocalTableInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table localtable
     *
     * @mbg.generated Thu Apr 29 18:03:24 CST 2021
     */
    int updateByPrimaryKey(LocalTableInfo record);
}