package com.wondersgroup.mapper;


import com.wondersgroup.entity.XueHuaInfo;
import org.apache.ibatis.annotations.Mapper;
import org.springframework.stereotype.Component;

import java.util.List;

@Mapper
@Component(value = "XueHuaInfoMapper")
public interface XueHuaInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuehua
     *
     * @mbg.generated Thu Apr 22 14:01:30 CST 2021
     */
    int deleteByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuehua
     *
     * @mbg.generated Thu Apr 22 14:01:30 CST 2021
     */
    int insert(XueHuaInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuehua
     *
     * @mbg.generated Thu Apr 22 14:01:30 CST 2021
     */
    XueHuaInfo selectByPrimaryKey(String id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuehua
     *
     * @mbg.generated Thu Apr 22 14:01:30 CST 2021
     */
    List<XueHuaInfo> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table xuehua
     *
     * @mbg.generated Thu Apr 22 14:01:30 CST 2021
     */
    int updateByPrimaryKey(XueHuaInfo record);


    List<XueHuaInfo> selectNew(String start);

    int updateEnd(XueHuaInfo record);
}